# Docker Compose principal - MediaHome
# Estrutura modular: cada serviço tem seu próprio arquivo na pasta correspondente
# Para iniciar todos: docker-compose up -d
# Para iniciar serviço específico: docker-compose -f jellyfin/jellyfin.yml up -d

include:
  # Serviços de mídia
  - jellyfin/jellyfin.yml
  - komga/komga.yml
  - koodoreader/koodoreader.yml
  - navidrome/navidrome.yml
  
  # Serviços de infraestrutura
  - fileserver/samba.yml
  - portainer/portainer.yml

# Serviços adicionais (backup)
services:
  # Backup automatizado
  backup:
    image: alpine:latest
    container_name: backup-configs
    restart: "no"
    volumes:
      - /mnt/config:/source:ro
      - /mnt/backup:/backup
    environment:
      - TZ=America/Sao_Paulo
    command: >
      sh -c "
        apk add --no-cache tar gzip &&
        while true; do
          echo 'Iniciando backup das configurações...' &&
          DATE=$$(date +%Y%m%d_%H%M%S) &&
          tar -czf /backup/mediahome_config_$$DATE.tar.gz -C /source . &&
          echo 'Backup criado: mediahome_config_'$$DATE'.tar.gz' &&
          find /backup -name 'mediahome_config_*.tar.gz' -mtime +30 -delete &&
          echo 'Backups antigos removidos (>30 dias)' &&
          echo 'Próximo backup em 24 horas...' &&
          sleep 86400
        done
      "
    networks:
      - mediahome

# Rede compartilhada entre todos os serviços
networks:
  mediahome:
    external: true
    name: app_network