# Docker Compose principal - MediaHome
# Estrutura modular: cada serviço tem seu próprio arquivo na pasta correspondente
# Para iniciar todos: docker-compose up -d
# Para iniciar serviço específico: docker-compose -f jellyfin/jellyfin.yml up -d

include:
  # Serviços de mídia
  - jellyfin/jellyfin.yml
  - komga/komga.yml
  - navidrome/navidrome.yml
  
  # Serviços de infraestrutura
  - fileserver/samba.yml
  - portainer/portainer.yml
  
  # Serviços de backup
  - backup/backup.yml

# Rede compartilhada entre todos os serviços
networks:
  mediahome:
    driver: bridge