# Samba - Produção (Ubuntu) — porta 445
# Para iniciar apenas este serviço em produção (Ubuntu):
#   docker compose -f fileserver/samba.ubuntu.yml up -d

services:
  samba:
    image: dperson/samba:latest
    container_name: samba-ubuntu
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - USER=suporte;suporte123
    volumes:
      # Compartilhamentos
      - /mnt/dados:/dados
      - /mnt/dados2:/dados2
      - /mnt/config:/config
    ports:
      # Mapear apenas a porta SMB moderna (445). O NetBIOS/139 é opcional
      # e geralmente já está em uso pelo serviço nativo (nmbd) no host.
      - "445:445"
    command: '-s "Dados;/dados;yes;no;no;all;none" -s "Dados2;/dados2;yes;no;no;all;none" -s "Config;/config;yes;no;no;all;none" -u "suporte;suporte123" -p'
    networks:
      - mediahome

networks:
  mediahome:
    external: true
    name: app_network