# Samba - Servidor de arquivos
# Para iniciar apenas este serviço: docker-compose -f fileserver/samba.yml up -d
# Para usar com compose principal: incluído automaticamente

services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - USER=suporte;suporte123
    volumes:
      # Compartilhamentos
      - /mnt/dados:/dados
      - /mnt/dados2:/dados2
      - /mnt/config:/config
    ports:
      - "139:139"
      - "1445:445"
    command: '-s "Dados;/dados;yes;no;no;all;none" -s "Dados2;/dados2;yes;no;no;all;none" -s "Config;/config;yes;no;no;all;none" -u "suporte;suporte123" -p'
    networks:
      - mediahome