# Jellyfin - Servidor de mídia
# Para iniciar apenas este serviço: docker-compose -f jellyfin/jellyfin.yml up -d
# Para usar com compose principal: incluído automaticamente

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      # Configurações no SSD
      - /mnt/config/jellyfin:/config
      # Pontos de montagem adicionais para facilitar navegação (raiz das mídias)
      - /mnt/dados:/media/dados:ro
      - /mnt/dados2:/media/dados2:ro
    ports:
      - "8096:8096"
    networks:
      - mediahome